begin;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  display_name text,
  email text,
  catchphrase text,
  avatar_url text,
  updated_at timestamptz not null default now(),
  gender text,
  birthday text,
  languages text,
  height text,
  work text,
  education text,
  kids text,
  relationship_type text,
  body_type text,
  exercise text,
  drinking text,
  smoking text,
  description text,
  location_label text,
  height_cm integer,
  religion text,
  is_metric boolean,
  location geometry(point, 4326),
  deleted_at timestamptz,
  is_hidden boolean not null default false,
  location_mode text not null default 'visible'
);

create table if not exists public.user_photos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  photo_url text,
  slot integer not null default 0,
  "order" integer not null default 0,
  position integer,
  deleted_at timestamptz
);

create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  is_hidden boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  min_age integer,
  max_age integer,
  max_distance_km double precision,
  preferred_genders text[] not null default '{}'::text[],
  location geometry(point, 4326),
  updated_at timestamptz not null default now()
);

create table if not exists public.blocks (
  id bigint generated by default as identity primary key,
  blocker uuid not null references auth.users(id) on delete cascade,
  blocked uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint blocks_unique unique (blocker, blocked)
);

create table if not exists public.swipe_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action in ('like', 'pass')),
  created_at timestamptz not null default now(),
  constraint swipe_events_user_target_unique unique (user_id, target_user_id)
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'profiles'
      and column_name = 'languages'
      and data_type = 'ARRAY'
  ) then
    alter table public.profiles
      alter column languages type text
        using array_to_string(languages, ', ');
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'profiles'
      and column_name = 'height'
      and data_type <> 'text'
  ) then
    alter table public.profiles
      alter column height type text using height::text;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'profiles'
      and column_name = 'kids'
      and data_type <> 'text'
  ) then
    alter table public.profiles
      alter column kids type text
        using case
          when kids is null then null
          when kids then 'i_have_kids'
          else 'i_dont_have_kids'
        end;
  end if;
end $$;

alter table public.user_photos drop column if exists storage_path;
alter table public.user_photos drop column if exists photo_path;
alter table public.user_photos drop column if exists used;
alter table public.user_photos drop column if exists created_at;
alter table public.user_photos drop column if exists is_main;

alter table public.swipe_events enable row level security;

drop policy if exists swipe_events_self on public.swipe_events;
create policy swipe_events_self
  on public.swipe_events
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

insert into public.user_settings (user_id)
select u.id
from auth.users u
left join public.user_settings s on s.user_id = u.id
where s.user_id is null;

create or replace function public.set_user_settings_updated_at()
returns trigger
language plpgsql
set search_path to 'public'
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_settings_updated_at on public.user_settings;
create trigger set_user_settings_updated_at
before update on public.user_settings
for each row
execute function public.set_user_settings_updated_at();

create or replace function public.create_user_settings_for_new_user()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  insert into public.user_settings (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists create_user_settings_after_auth_insert on auth.users;
create trigger create_user_settings_after_auth_insert
after insert on auth.users
for each row
execute function public.create_user_settings_for_new_user();

create or replace function public.delete_account_data_v2()
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  update public.profiles
  set
    deleted_at = now(),
    is_hidden = true,
    updated_at = now()
  where user_id = auth.uid()
    and deleted_at is null;
end;
$$;

create or replace function public.get_discovery_feed_v2(
  p_limit integer default 20,
  p_offset integer default 0
) returns table(
  profile_id bigint,
  user_id uuid,
  display_name text,
  age integer,
  gender text,
  catchphrase text,
  description text,
  avatar_url text,
  distance_km double precision,
  photos jsonb,
  location_label text,
  work text,
  education text,
  kids text,
  relationship_type text,
  religion text,
  body_type text,
  exercise text,
  drinking text,
  smoking text,
  height text,
  languages text
)
language sql
stable
security definer
set search_path to 'public'
as $$
  with me as (
    select p.user_id, p.location, pref.min_age, pref.max_age, pref.max_distance_km, pref.preferred_genders
    from public.profiles p
    left join public.user_preferences pref on pref.user_id = p.user_id
    where p.user_id = auth.uid()
    limit 1
  ),
  candidates as (
    select
      p.*,
      case
        when p.birthday ~ '^\d{4}-\d{2}-\d{2}$'
        then date_part('year', age(p.birthday::date))::int
        else null
      end as age_years
    from public.profiles p
  )
  select
    p.id,
    p.user_id,
    p.display_name,
    p.age_years,
    p.gender,
    p.catchphrase,
    p.description,
    p.avatar_url,
    case
      when (select location from me) is null or p.location is null then null
      else st_distance((select location from me), p.location) / 1000.0
    end,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', up.id,
            'path', up.photo_url,
            'position', up.position
          )
          order by up.position
        )
        from public.user_photos up
        where up.user_id = p.user_id
          and up.deleted_at is null
          and up.photo_url is not null
      ),
      '[]'::jsonb
    ),
    p.location_label,
    p.work,
    p.education,
    p.kids,
    p.relationship_type,
    p.religion,
    p.body_type,
    p.exercise,
    p.drinking,
    p.smoking,
    p.height,
    p.languages
  from candidates p
  cross join me
  where p.user_id <> auth.uid()
    and p.deleted_at is null
    and p.is_hidden = false
    and p.location_mode <> 'invisible'
    and (me.preferred_genders is null or cardinality(me.preferred_genders) = 0 or p.gender ilike any(me.preferred_genders))
    and (me.min_age is null or p.age_years is null or p.age_years >= me.min_age)
    and (me.max_age is null or p.age_years is null or p.age_years <= me.max_age)
    and (
      me.max_distance_km is null
      or me.location is null
      or p.location is null
      or st_dwithin(me.location, p.location, me.max_distance_km * 1000.0)
    )
    and not exists (
      select 1
      from public.swipe_events s
      where s.user_id = auth.uid()
        and s.target_user_id = p.user_id
    )
    and not exists (
      select 1
      from public.blocks b
      where (b.blocker = auth.uid() and b.blocked = p.user_id)
         or (b.blocker = p.user_id and b.blocked = auth.uid())
    )
  order by (
    case
      when (select location from me) is null or p.location is null then null
      else st_distance((select location from me), p.location) / 1000.0
    end
  ) nulls last, p.updated_at desc
  limit greatest(0, p_limit)
  offset greatest(0, p_offset);
$$;

create or replace function public.get_nearby_profiles_v2(
  p_radius_km integer default 25,
  p_limit integer default 50
) returns table(
  profile_id bigint,
  user_id uuid,
  display_name text,
  age integer,
  gender text,
  avatar_url text,
  location_label text,
  distance_km double precision
)
language sql
stable
security definer
set search_path to 'public'
as $$
  with me as (
    select location
    from public.profiles
    where user_id = auth.uid()
    limit 1
  ),
  candidates as (
    select
      p.*,
      case
        when p.birthday ~ '^\d{4}-\d{2}-\d{2}$'
        then date_part('year', age(p.birthday::date))::int
        else null
      end as age_years
    from public.profiles p
  )
  select
    p.id,
    p.user_id,
    p.display_name,
    p.age_years,
    p.gender,
    p.avatar_url,
    p.location_label,
    st_distance((select location from me), p.location) / 1000.0
  from candidates p
  where p.user_id <> auth.uid()
    and p.deleted_at is null
    and p.is_hidden = false
    and p.location_mode <> 'invisible'
    and (select location from me) is not null
    and p.location is not null
    and st_dwithin((select location from me), p.location, p_radius_km * 1000.0)
    and not exists (
      select 1
      from public.blocks b
      where (b.blocker = auth.uid() and b.blocked = p.user_id)
         or (b.blocker = p.user_id and b.blocked = auth.uid())
    )
  order by st_distance((select location from me), p.location)
  limit greatest(0, p_limit);
$$;

commit;
