begin;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  display_name text,
  email text,
  catchphrase text,
  avatar_url text,
  updated_at timestamptz not null default now(),
  gender text,
  birthday text,
  languages text,
  height text,
  work text,
  education text,
  kids text,
  relationship_type text,
  body_type text,
  exercise text,
  drinking text,
  smoking text,
  description text,
  location_label text,
  height_cm integer,
  religion text,
  is_metric boolean,
  location geometry(point, 4326),
  deleted_at timestamptz,
  is_hidden boolean not null default false,
  location_mode text not null default 'visible'
);

create table if not exists public.user_photos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  photo_url text,
  photo_path text,
  storage_path text,
  slot integer not null default 0,
  "order" integer not null default 0,
  position integer,
  is_main boolean not null default false,
  deleted_at timestamptz
);

create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  is_hidden boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  min_age integer,
  max_age integer,
  max_distance_km double precision,
  preferred_genders text[] not null default '{}'::text[],
  location geometry(point, 4326),
  updated_at timestamptz not null default now()
);

create table if not exists public.blocks (
  id bigint generated by default as identity primary key,
  blocker uuid not null references auth.users(id) on delete cascade,
  blocked uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint blocks_unique unique (blocker, blocked)
);

commit;
